version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "09:00"
      timezone: "Europe/Berlin"
    commit-message:
      prefix: "ci"
    reviewers:
      - "juliangruber"
      - "pyropy"
